const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC_RI = path.join(ROOT, 'ri');
const DIST = path.join(ROOT, 'dist');
const DIST_RI = path.join(DIST, 'ri');
const CONFIG_FILE = path.join(ROOT, 'config.json');

// Helper: Shuffle Array (Fisher-Yates)
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Main function
function build() {
    console.log('Starting build...');

    // Load Config
    let config = { domain: '' };
    
    // Priority 1: Environment Variable
    if (process.env.DOMAIN) {
        config.domain = process.env.DOMAIN;
        console.log('Loaded domain from environment variable.');
    } 
    // Priority 2: Config File
    else if (fs.existsSync(CONFIG_FILE)) {
        try {
            const configContent = fs.readFileSync(CONFIG_FILE, 'utf8');
            const parsed = JSON.parse(configContent);
            if (parsed.domain) {
                config.domain = parsed.domain;
            }
            console.log('Loaded domain from config.json.');
        } catch (e) {
            console.warn('Failed to parse config.json, using default settings.');
        }
    }

    // Normalize domain (remove trailing slash)
    if (config.domain) {
        config.domain = config.domain.replace(/\/$/, '');
    }

    console.log(`Using domain prefix: "${config.domain}"`);

    // 1. Clean/Create Dist
    if (fs.existsSync(DIST)) {
        fs.rmSync(DIST, { recursive: true, force: true });
    }
    fs.mkdirSync(DIST, { recursive: true });
    fs.mkdirSync(DIST_RI, { recursive: true });

    // 2. Process Folders
    const types = ['h', 'v'];
    let counts = {};
    
    types.forEach(type => {
        const srcFolder = path.join(SRC_RI, type);
        const distFolder = path.join(DIST_RI, type);
        
        if (!fs.existsSync(srcFolder)) {
            console.warn(`Source folder not found: ${srcFolder}`);
            counts[type] = 0;
            return;
        }

        fs.mkdirSync(distFolder, { recursive: true });

        // Read and Filter Images
        let files = fs.readdirSync(srcFolder).filter(f => f.match(/\.(webp|jpg|jpeg|png|gif)$/i));
        
        // Shuffle
        files = shuffle(files);

        // Copy and Rename
        files.forEach((file, index) => {
            const srcPath = path.join(srcFolder, file);
            // User requested 1.webp, 2.webp, etc.
            const destPath = path.join(distFolder, `${index + 1}.webp`);
            fs.copyFileSync(srcPath, destPath);
        });

        counts[type] = files.length;
        console.log(`Processed ${type}: ${counts[type]} images.`);
    });

    // 3. Generate Single JS
    const jsContent = `
/**
 * Static Random Pic API
 * Generated by build script
 */
(function() {
    var counts = ${JSON.stringify(counts)};
    var domain = '${config.domain}';
    
    // State management for session consistency
    var sessionRandomH = null;
    var sessionRandomV = null;

    // Helper: Get random URL for a type (h or v), persistent per session
    function getRandomUrl(type) {
        if (!counts[type] || counts[type] === 0) return '';
        
        // Return existing session URL if available
        if (type === 'h' && sessionRandomH) return sessionRandomH;
        if (type === 'v' && sessionRandomV) return sessionRandomV;

        // Generate new if not exists
        var num = Math.floor(Math.random() * counts[type]) + 1;
        var url = domain + '/ri/' + type + '/' + num + '.webp';

        // Save to session state
        if (type === 'h') sessionRandomH = url;
        if (type === 'v') sessionRandomV = url;

        return url;
    }

    // Expose global functions
    window.getRandomPicH = function() { return getRandomUrl('h'); };
    window.getRandomPicV = function() { return getRandomUrl('v'); };

    // 1. Logic for Background (Customized based on user request)
    function setRandomBackground() { 
         // Get random URL using the helper (Dynamic count & domain)
         const bgUrl = getRandomUrl('h');
          
         // Find the background box element 
         const bgBox = document.getElementById('bg-box'); 
          
         if (bgBox) { 
             // Preload image 
             const img = new Image(); 
             img.onload = function() { 
                 bgBox.style.backgroundImage = \`url('\${bgUrl}')\`; 
                 bgBox.classList.add('loaded'); 
                 console.log('Random background loaded:', bgUrl); 
                  
                 // Set CSS variables for transparency effects 
                 document.documentElement.style.setProperty('--card-bg', 'var(--card-bg-transparent)'); 
                 document.documentElement.style.setProperty('--float-panel-bg', 'var(--float-panel-bg-transparent)'); 
             }; 
             img.onerror = function() { 
                 console.error('Failed to load background image:', bgUrl); 
             }; 
             img.src = bgUrl; 
         } else { 
             // Fallback: If no #bg-box, check for data-random-bg for backward compatibility/other elements
             // This keeps the generic functionality available if needed, but prioritizes the user's specific logic above.
             initGenericBackgrounds();
         } 
    }

    // 2. Logic for Image Tags (Generic)
    function initImgTags() {
        var imgTags = document.getElementsByTagName('img');
        for (var i = 0; i < imgTags.length; i++) {
            var img = imgTags[i];
            var alt = img.getAttribute('alt');
            var src = img.getAttribute('src');

            if (alt === 'random:h' || (src && src.indexOf('/random/h') !== -1)) {
                img.src = getRandomUrl('h');
            } else if (alt === 'random:v' || (src && src.indexOf('/random/v') !== -1)) {
                img.src = getRandomUrl('v');
            }
        }
    }

    // Helper for generic data-random-bg (as a backup or secondary feature)
    function initGenericBackgrounds() {
        var bgElements = document.querySelectorAll('[data-random-bg]');
        bgElements.forEach(function(el) {
            // Skip if it is the bg-box we already handled (though setRandomBackground handles #bg-box specifically)
            if (el.id === 'bg-box') return;

            var type = el.getAttribute('data-random-bg');
            if (type === 'h' || type === 'v') {
                var url = getRandomUrl(type);
                if (url) {
                    var img = new Image();
                    img.onload = function() {
                        el.style.backgroundImage = 'url("' + url + '")';
                        el.classList.add('loaded');
                    };
                    img.src = url;
                }
            }
        });
    }

    function init() {
        setRandomBackground();
        initImgTags();
    }
  
    // Run on initial load 
    if (document.readyState === 'loading') { 
        document.addEventListener('DOMContentLoaded', init); 
    } else { 
        init(); 
    } 
  
    // Swup integration
    function setupSwup() {
        if (window.swup && window.swup.hooks) {
            // Register hook for content replacement
            window.swup.hooks.on('content:replace', init);
            console.log('Random Pic API: Registered with Swup hooks.');
        }
    }

    if (window.swup) {
        setupSwup();
    } else {
        document.addEventListener('swup:enable', setupSwup);
    }

    // Legacy Swup support
    document.addEventListener('swup:contentReplaced', init); 
})();
`;
    fs.writeFileSync(path.join(DIST, 'random.js'), jsContent.trim());

    // Copy index.html if exists and not empty
    const indexSrc = path.join(ROOT, 'index.html');
    if (fs.existsSync(indexSrc)) {
         const stats = fs.statSync(indexSrc);
         if (stats.size > 0) {
             fs.copyFileSync(indexSrc, path.join(DIST, 'index.html'));
             console.log('Copied index.html to dist');
         } else {
             console.log('index.html is empty, creating a demo page in dist...');
             createDemoHtml();
         }
    } else {
        createDemoHtml();
    }
    
    console.log('Build complete. Output is in /dist folder.');
}

function createDemoHtml() {
    const htmlContent = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Static Random Pic API Demo</title>
    <style>
        body { font-family: sans-serif; max-width: 800px; margin: 20px auto; padding: 20px; }
        .card { border: 1px solid #ccc; padding: 20px; margin-bottom: 20px; border-radius: 8px; }
        img { max-width: 100%; height: auto; border-radius: 4px; display: block; background: #eee; min-height: 200px; }
        .btn { display: inline-block; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 4px; }
        .bg-box { width: 100%; height: 200px; background-size: cover; background-position: center; border-radius: 4px; border: 1px dashed #999; display: flex; align-items: center; justify-content: center; color: white; text-shadow: 0 1px 3px rgba(0,0,0,0.8); font-weight: bold; }
    </style>
</head>
<body>
    <h1>Static Random Pic API (Client-Side)</h1>
    <p>This is a static implementation. Images are randomized at build time.</p>

    <div class="card">
        <h2>Horizontal Image (横屏)</h2>
        <p>Using <code>&lt;img alt="random:h"&gt;</code>:</p>
        <!-- Logic: Script finds alt="random:h" and sets src -->
        <img alt="random:h" title="Random Horizontal Image" />
        <br>
        
        <p>Background Image (<code>data-random-bg="h"</code>):</p>
        <!-- Logic: Script finds data-random-bg="h" and sets style.backgroundImage -->
        <div class="bg-box" data-random-bg="h">
            Background Image
        </div>
    </div>

    <div class="card">
        <h2>Vertical Image (竖屏)</h2>
        <p>Using <code>&lt;img alt="random:v"&gt;</code>:</p>
        <img alt="random:v" style="max-height: 400px;" title="Random Vertical Image" />
    </div>

    <!-- Import the single generated script -->
    <script src="random.js"></script>
</body>
</html>`;
    fs.writeFileSync(path.join(DIST, 'index.html'), htmlContent);
    console.log('Created demo index.html in dist');
}

build();
