const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC_RI = path.join(ROOT, 'ri');
const DIST = path.join(ROOT, 'dist');
const DIST_RI = path.join(DIST, 'ri');
const CONFIG_FILE = path.join(ROOT, 'config.json');

// Helper: Shuffle Array (Fisher-Yates)
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Main function
function build() {
    console.log('Starting build...');

    // Load Config
    let config = { domain: '' };
    
    // Priority 1: Environment Variable
    if (process.env.DOMAIN) {
        config.domain = process.env.DOMAIN;
        console.log('Loaded domain from environment variable.');
    } 
    // Priority 2: Config File
    else if (fs.existsSync(CONFIG_FILE)) {
        try {
            const configContent = fs.readFileSync(CONFIG_FILE, 'utf8');
            const parsed = JSON.parse(configContent);
            if (parsed.domain) {
                config.domain = parsed.domain;
            }
            console.log('Loaded domain from config.json.');
        } catch (e) {
            console.warn('Failed to parse config.json, using default settings.');
        }
    }

    // Normalize domain (remove trailing slash)
    if (config.domain) {
        config.domain = config.domain.replace(/\/$/, '');
    }

    console.log(`Using domain prefix: "${config.domain}"`);

    // 1. Clean/Create Dist
    if (fs.existsSync(DIST)) {
        fs.rmSync(DIST, { recursive: true, force: true });
    }
    fs.mkdirSync(DIST, { recursive: true });
    fs.mkdirSync(DIST_RI, { recursive: true });

    // 2. Process Folders
    const types = ['h', 'v'];
    
    types.forEach(type => {
        const srcFolder = path.join(SRC_RI, type);
        const distFolder = path.join(DIST_RI, type);
        
        if (!fs.existsSync(srcFolder)) {
            console.warn(`Source folder not found: ${srcFolder}`);
            return;
        }

        fs.mkdirSync(distFolder, { recursive: true });

        // Read and Filter Images
        let files = fs.readdirSync(srcFolder).filter(f => f.match(/\.(webp|jpg|jpeg|png|gif)$/i));
        
        // Shuffle
        files = shuffle(files);

        // Copy and Rename
        files.forEach((file, index) => {
            const srcPath = path.join(srcFolder, file);
            // User requested 1.webp, 2.webp, etc.
            const destPath = path.join(distFolder, `${index + 1}.webp`);
            fs.copyFileSync(srcPath, destPath);
        });

        const count = files.length;
        console.log(`Processed ${type}: ${count} images.`);

        // 3. Generate JS
        // The user wants a script that replaces a special link in an HTML form.
        // We will provide a function and an auto-runner.
        const jsContent = `
/**
 * Static Random Pic API - ${type.toUpperCase()} (Horizontal/Vertical)
 * Generated by build script
 */
(function() {
    var total = ${count};
    var type = '${type}';
    var domain = '${config.domain}';
    
    // Function to get a random URL
    function getRandomUrl() {
        var num = Math.floor(Math.random() * total) + 1;
        // Using configured domain + absolute path
        return domain + '/ri/' + type + '/' + num + '.webp';
    }

    // Expose global function
    window['getRandomPic' + type.toUpperCase()] = getRandomUrl;

    // Auto-replace logic
    // Finds elements with src="random:{type}" or href="random:{type}" and updates them
    document.addEventListener('DOMContentLoaded', function() {
        var url = getRandomUrl();
        var placeholder = 'random:' + type;
        
        // Update elements with special href
        var linkElements = document.querySelectorAll('[href="' + placeholder + '"]');
        linkElements.forEach(function(el) {
            el.href = url;
        });

        // Update elements with special src
        var srcElements = document.querySelectorAll('[src="' + placeholder + '"]');
        srcElements.forEach(function(el) {
            el.src = url;
        });
        
        console.log('Random Pic ' + type.toUpperCase() + ' updated elements with placeholder: ' + placeholder);
    });
})();
`;
        fs.writeFileSync(path.join(DIST, `random-${type}.js`), jsContent.trim());
    });

    // Copy index.html if exists and not empty
    const indexSrc = path.join(ROOT, 'index.html');
    if (fs.existsSync(indexSrc)) {
         const stats = fs.statSync(indexSrc);
         if (stats.size > 0) {
             fs.copyFileSync(indexSrc, path.join(DIST, 'index.html'));
             console.log('Copied index.html to dist');
         } else {
             console.log('index.html is empty, creating a demo page in dist...');
             createDemoHtml();
         }
    } else {
        createDemoHtml();
    }
    
    console.log('Build complete. Output is in /dist folder.');
}

function createDemoHtml() {
    const htmlContent = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Static Random Pic API Demo</title>
    <style>
        body { font-family: sans-serif; max-width: 800px; margin: 20px auto; padding: 20px; }
        .card { border: 1px solid #ccc; padding: 20px; margin-bottom: 20px; border-radius: 8px; }
        img { max-width: 100%; height: auto; border-radius: 4px; }
        .btn { display: inline-block; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 4px; }
    </style>
</head>
<body>
    <h1>Static Random Pic API (Client-Side)</h1>
    <p>This is a static implementation. Images are randomized at build time.</p>

    <div class="card">
        <h2>Horizontal Image (横屏)</h2>
        <!-- The JS will find src="random:h" and update src -->
        <img src="random:h" alt="Loading random horizontal image..." />
        <br><br>
        <p>Link example (HTML Form/Link replacement):</p>
        <!-- The JS will find href="random:h" and update href -->
        <a href="random:h" class="btn" target="_blank">Open Random Horizontal Image</a>
    </div>

    <div class="card">
        <h2>Vertical Image (竖屏)</h2>
        <!-- The JS will find src="random:v" and update src -->
        <img src="random:v" alt="Loading random vertical image..." style="max-height: 400px;" />
        <br><br>
        <p>Link example:</p>
        <!-- The JS will find href="random:v" and update href -->
        <a href="random:v" class="btn" target="_blank">Open Random Vertical Image</a>
    </div>

    <!-- Import the generated scripts -->
    <script src="random-h.js"></script>
    <script src="random-v.js"></script>
</body>
</html>`;
    fs.writeFileSync(path.join(DIST, 'index.html'), htmlContent);
    console.log('Created demo index.html in dist');
}

build();
